### ISSUE TITLE
파일 정리 다 했습니다.

### ISSUE THREAD

**Issue by fora22** [fora22/Coding_Test#1]
# 근황
- Local에는 *VS* 폴더도 있는데 내부에 아무것도 없어서 그런지 안올라 갔네요...ㅎ;;;
- 책은 방금 주문했습니다.(쿠팡 로켓배송이 참 좋은 것 같아요...ㅎㅎ)
# 추가 질문
- Projects나 Milestone 도 정해야 될까요?
- 멘토링이면 1주에 한번은 미팅 가지는게 좋겠죠?

**Comment by fora22** [comment]
# 추가로 더 질문!!
- Branch는 Develope branch 하나를 할까요? 아니면 혹시 생각해두신 규칙이 있을까요? ㅎㅎ

**Comment by jongfeel** [comment]
Projects의 경우는 내 진행 상황 체크를 위해 사용하는 걸로 issue, pull request와 연계해서 사용하면 좋습니다.
- To do, In Progress, Done의 상태로 Issue에 연결시켜 체크를 계속 해주시면 스스로 상황 파악하고 앞으로 계획 잡는데 좋을거에요

Milestone의 경우는 하나의 작은 목표 단위라고 생각하면 됩니다.
종료 날짜를 정하고 어떤 단위를 해 해야할지를 두는 거죠.
보통 오픈소스 소프트웨어는 버전 단위로 많이 하는데
대원님 같은 경우는 챕터 단위나 개념 단위(Stack, Queue)로 해보면 좋을 것 같네요

멘토링 미팅은 원하는 주기를 정하면 됩니다.
그리고 그 주기 안에 다른 일이 생겨서 작업을 못했거나 하면 연기해도 되요.
스스로 시간 투자할 수 있는 스케줄대로 정해주시면 됩니다.
지금 제 개인 멘티 분들은
- 화요일 2주 간격
- 수요일 2주 간격
- 목요일 2주 간격
으로 다 2주 간격입니다.

만약에 다른 분들과 안겹치게 하시려면 월, 금요일을 선택하시면 되고
2주 간격으로 진행하고 싶으시다면 화,수,목 하시는 분들 안하는 주에 하면 가능합니다.

Branch는 develop로 해도 상관 없어 보이네요.
그런데 보통은 코딩 문제를 다 풀고 완성된 걸 올리고 싶어하기 때문에 
branch의 경우는 이후 변경되거나 바뀌는 부분을 기록으로 남기고 싶을 때 pull request로 해 두면 
그냥 main branch commit log 보는 거 보다 훨씬 좋겠죠?

**Comment by fora22** [comment]
미팅은 화요일 2주 간격이 좋을 것 같습니다!!

**Comment by jongfeel** [comment]
첫 온라인 리뷰 미팅은 10월 27일로 하면 좋을 것 같습니다.
- 10월 20일은 짧은 감이 있고
- 11월 3일은 화요일날 하시는 태원님이 하는 날이라서요.

그리고 일정 조절이 필요할 때가 되면 제 스케줄링 페이지를 가끔 참고하셔서 요청해 주세요

https://www.notion.so/Mentoring-schedule-9b78ed7c4289409a858a96fbea783b42

**Comment by fora22** [comment]
아 제가 26~27일에는 대전에 교육들으러 가서 힘들것 같습니다. 29~30은 신청은 해놨는데 대기자 상태라서 어떻게 될지 모르겠구 28일에는 온라인 교육이긴 하지만 저녁에는 시간이 될 것 같습니다. 28일 저녁 괜찮으신가요?

**Comment by jongfeel** [comment]
그러면 그냥 다음 주 쯤에 해야 겠네요.
다음 주 20, 21, 22, 23 중에 하루를 정하면 될 거 같아요.

아 그리고 멘토링 시간은 평일이기 때문에 오후 11시에 합니다.
제가 급작스럽게 야근을 할 수도 있기 때문에 그렇습니다.

**Comment by fora22** [comment]
23일이 좋을 것 같습니다! ㅎㅎ
오후 11시면 집에서 해야겠네요. 캠은 없는데 상관 없을까요?

**Comment by jongfeel** [comment]
캠 없어도 됩니다. 화면 공유로 화면 보고 하는게 더 중요하니까요.

그럼 23일로 첫 리뷰 일정을 잡을게요.

**Comment by fora22** [comment]
넵 알겠습니다! ㅎㅎ
