### ISSUE TITLE
Refactroing에 대한 의견

### ISSUE THREAD

**Issue by jongfeel** [fora22/Coding_Test#12]
refactoring에 대해 상당히 관심이 많으신 듯 해서 의견을 얘기해 보려고 합니다.

1. 효율적인 코드 작성이 리팩토링?

리팩토링 == 효율적인 코드 라고 생각하셨다면 false 입니다.
가끔 착각하고 있는 사람도 있어서요.
여러분들이 생각하는 효율은 문제가 없는 알고리즘, 시간/공간 복잡도가 개선된 코드로 생각하실 수 있는데
실제 리팩토링은 기능이 변경되지 않고 코드를 `개선` 시키는 작업입니다.
그 안에 효율적인 코드도 포함될 수 있지만 큰 알고리즘 적인 변경이나 성능 개선은 포함이 안되는게 맞아요.

2. 리팩토링에 대한 질문?

실제로 리팩토링을 진행해 보시고 어떤 필요에 의해서 이렇게 리팩토링을 진행했다 정도로 pull request를 주시는 정도가 좋습니다.
리팩토링을 해야 하는지, 어떻게 해야 하는지에 대한 내용까지 제가 리뷰해드릴 수 있겠지만
그러면 리팩토링을 제가 하는 것이지 여러분이 하는게 아닌게 되므로 리팩토링을 하는게 큰 의미가 없습니다.

**Comment by fora22** [comment]
대전 교육이 끝나서 지금 제대로 읽었네요.
# 1. 
저는 효율적인 코드 라고 생각했는데 결이 조금 다른가 보네요. 리팩토링은 그럼 가독성(readability)을 높이고 short 코딩을 하도록 하는 것을 뜻하는걸까요?

# 2.
방법에 대해 알겠습니다. 다만 한 가지 물어보고 싶은게 PR을 위해서는 비교할 branch가 2개 필요한데 Feature branch에서 작업하다 보면 어느새 커밋이 10개가 넘어가고 그렇습니다. PR을 위해서는 기능이나 소스코드 변경내역, review가 필요한 issue만 file change에 넣는게 좋을 것 같은데, 현재는 PR을 위해서 `Feature/~~ ` branch에서 `Feature/~~/PR` branch를 만들어 PR을 올리고 있습니다. file change가 명확해서 PR하기는 쉽지만 branch가 너무 많아지는 것 같아서요.. 혹시 의견사항 있으실까요?

**Comment by jongfeel** [comment]
1. 중복 코드 제거와 언급한 내용을 포함해서 더 폭 넓은 뜻을 가지고 있습니다. 확실한건 성능 개선은 아니라는 것이죠. 효율이라는 단어가 적절하지 못해서 그런건데, 효율을 성능으로 잘못 이해하지만 않으면 됩니다. 

2. 한번에 많은 걸 하려고 해서 그렇습니다. PR을 여러번 줘도 상관 없으니 시간 순서에만 맞에 merge가 일어난다면 큰 문제는 없을 거에요.
PR마다 한가지 목적의 리뷰를 한다면 branch가 많아지는 건 상관 없습니다. branch가 많아지는게 문제라고 생각되면 merge 이후에 branch를 삭제해도 됩니다.

**Comment by JSY8869** [comment]
의견 감사합니다!!
리팩토링의 의미는 알고 있었는데 항상 효율이 문제가 있었던 것 같습니다...
혹시나 제가 코딩을 하는 데 있어서 안좋은 습관이나 메모리 낭비같은게 보이는 경우에는 리팩토링에 대해 언급해 주시면 잘 수정해보도록 하겠습니다!!

**Comment by jongfeel** [comment]
> 의견 감사합니다!!
> 리팩토링의 의미는 알고 있었는데 항상 효율이 문제가 있었던 것 같습니다...
> 혹시나 제가 코딩을 하는 데 있어서 안좋은 습관이나 메모리 낭비같은게 보이는 경우에는 리팩토링에 대해 언급해 주시면 잘 수정해보도록 하겠습니다!!

그럴때는 리팩토링이라는 용어 보다는 다음과 같은 용어가 적절할 것 같습니다.
- 안 좋은 습관 => 코드 리뷰를 통한 개선
- 메모리 낭비 => 문제점 수정 혹은 성능 개선
