### ISSUE TITLE
3rd plan by JSY

### ISSUE THREAD

**Issue by JSY8869** [fora22/Coding_Test#18]
# 목표
## 이것이 코딩 테스트다
- [x] 3-3번 숫자 카드 게임
- [x] 3-4번 1이 될 때까지
- [x] 4-1 상하좌우
- [x] 4-2 시각
## Test case
- [x] Test case 생성 알고리즘 만들기
### 1주당 6시간
- 평일 3시간
- 주말 3시간
3rd review에 대한 계획이라 3rd plan으로 했습니다!

**Comment by jongfeel** [comment]
저도 오타 발견했어요. 3nd 아니고 3rd 입니다 ㅎㅎ

**Comment by JSY8869** [comment]
아이고 수정했습니다!! 감사합니다ㅎㅎ
