### ISSUE TITLE
Planning to next

### ISSUE THREAD

**Issue by jongfeel** [fora22/Coding_Test#19]
#18 
세영님이 하신 것과 같이 대원님도 계획을 올려주고 진행하셨으면 좋겠습니다.

**Comment by fora22** [comment]
네 요즘 이상하게 시간이 빠듯하네요. 대부분은 제가 꽂혀서 그렇지만...ㅎㅎ

사실 어제 올려야겠다 생각은 들었는데 Notion [GTD](https://m.blog.naver.com/hasajon/220648576335) 템플릿을 직접 만드느라 시간을 다 보냈네요.

약간 홍보를 드리자면 GTD를 참고하여 to do list를 새로 만들었는데 멘토님도 따로 쓰시는 to do list 가 없으시다면 나중에 템플릿 Duplicate해서 써보시면 좋을 것 같습니다. 이미 to do list 는 있을것 같긴 하지만요 ㅎㅎ

계획은 오늘내로 지금(#19) 이슈에 올리도록 하겠습니다,.!

**Comment by fora22** [comment]
어제 정말 [이것](https://www.notion.so/fora22/GTD-Dashboard-Template-871d83c07d8242d08767cbfd5b65afbb) 때문에...4~5시간을 쓴 것 같군요..ㅎㅎ

**Comment by fora22** [comment]
# 목표 이전에
이전에 말씀드리긴 했는데...제가 이것 저것 호기심이 많은 편이라 요거 해보고 저거 해보고 하는 경향이 조금 셉니다. 그래서 지금 Study 이외에도 해오고 있던게 있는데(아직 진행도가 초반이지만)
## [FlowDebugger 프로젝트](https://github.com/GKO95/UWP.FlowDebugger)
- 동아리 선배가 회사에서 이거 있으면 좋겠다 싶어서 [UWP](https://docs.microsoft.com/ko-kr/windows/uwp/get-started/universal-application-platform-guide)를 활용하여 만들어보는중
- 제가 Front, [형](https://github.com/GKO95)이 Back이지만 서로 바쁘다는 핑계로...(사실 제가 안함...)아직 진행이 더딤..ㅎㅎ

## 블로그 만들기
### 어떻게 된거냐면...
아는 친구중에 장신구 관련 전공인 친구가 있는데 자기의 작품(?)을 보관할 수 있는 블로그가 있으면 좋겠다고 함. 그래서 블로그 만드는거 같이 해줄 수 있냐고 저에게 물어봄. 이전부터 개인 블로그 직접 만드는게 소박한 버킷 리스트라 흔쾌히 수락. 화면 디자인은 미대 친구에게 맡기고 저는 Node.js를 활용한 서버를 맡음. 그래서 [JS](https://github.com/fora22/VanillaJS)도 공부해 봄. 이제 Node.js를 할 차례
### 그럼 지금은?
- 아직 레포지토리도 만들지 못한 상태
- 교육 자료로는 [생활코딩 Node.js](https://opentutorials.org/course/3332)를 추천받아서 강의를 들어볼 생각중

## [C++ Socket 통신](https://github.com/fora22/cpp_Network)
- 학교 교수님에게 지도받으면서 하는 Socket 통신 공부
- 최종적인 목표는 통신 Application(Desktop)을 만드는 것.
- 2020년 초에 팀원들과 하다가 우선순위에 밀려 보류 됐다가, 현재는 혼자 하는중

## [뉴스크롤러](https://github.com/fora22/NewsCrawler)
- 자소서나 면접 준비할 때 해당기업의 기사를 읽어볼 필요가 있는데 일일히 클릭하고 지우고 하기가 힘들 것 같아서 만들어 봄. 
- 네이버 기사에서 긁어오는 형식인데, 검색어를 설정할 수 있음.
- 엑셀로 저장하기 때문에 해당 기업의 중요한 키워드가 들어간 기사를 고를 수 있음


# 목표

## [FlowDebugger 프로젝트](https://github.com/GKO95/UWP.FlowDebugger)
- 버튼을 누르면 해당 모양이 그려지도록 만들기
    - [ ] 사각형
    - [ ] 마름모
    - [ ] 동그라미

## [C++ Socket 통신](https://github.com/fora22/cpp_Network)
- [ ] pthread를 활용하여 비동기 송수신 멀티 스레드 구현(Server, Client)

## Data Structure
- [ ] Stack(Linked List)의 가독성 문제 [리팩토링](https://github.com/fora22/Coding_Test/pull/10#issuecomment-720283179)
- [ ] Queue 구조 Linked List 구현

##  이것이 코딩 테스트다
- [ ] 3-3번 숫자 카드 게임
- [ ] 3-4번 1이 될 때까지

# 질문
혹시 괜찮으시다면 해당 프로젝트들도 나중에 질문이나 PR올리게 되면 review 해주실 수 있을까요?

# 시간
## 1주당 8시간
- 평일 6시간

- 주말 2시간(토, 일 합쳐서) -> 단, 11/6 ~ 11/9는 가족여행이므로 7,8일은 제외

**Comment by jongfeel** [comment]
내용이 상당히 많아서 저도 다 조금씩 파악하는데 시간이 좀 걸리는 군요.

## 우선 저의 조언은

### 일을 시작하고 끝을 내는 경험

시작한 일에 대해 끝을 보셨으면 좋겠습니다.
어떻게 보면 "안하느니만도 못한" 일을 벌여 놓고 시간만 보냈던 흑역사로 남을 수도 있거든요.

저도 그런 흑역사가 많이 있긴 한데,
그건 그거대로 흑역사로 두고 지금은 그렇게 하지 않으려고 합니다.
끝을 언제 내겠다는 목표와 계획을 세우면 거의 그런 일은 일어나지 않는다는 걸 알았거든요.

### 거창한걸 하려고 하지 말고 작은 목표로 나눠서 하자

제일 미련한 목표가 "Node.js 완전정복" 같은 목표입니다.
적어도 2주 아무리 길어도 1달 안에 할 수 있는 구체적이고도 작은 목표를 세우고 계획하고 실천해야 합니다.
"Node.js 설치 및 hello world 출력" 정도면 1일치 계획으로 충분할 수 있겠죠?

### 선택과 집중

일을 벌여놔도 선택과 집중 전략대로 하다 보면
소홀히 대했던 일에 대해 내 맘은 그렇지 않은데 소홀해질 수도 있긴 합니다.
그러므로 아예 3달이나 지나 버렸거나 언젠가 할 수 있고 당장이라도 할 수 있을 것 같지만
손도 안대고 있는 건 과감하게 drop 해야 합니다.

## 이제 저의 대답은 이렇습니다.

### 각 프로젝트 별로 README.md에 다음과 같은 내용 필요.

- Overview: 뭘 하는 프로그램인지
- Document
  - Development Environment: 이 프로젝트를 하려면 어떤 개발 환경이 필요한지
  - Build and Run: 빌드와 실행은 어떻게 하면 되는지
  - Manual: 실행 후 사용 방법에 대한 내용 
- License: 라이선스 조항은 어떻게 되는지
- Contributing: 기여하려면 어떤 조건과 방법으로 해야 하는지
- Known issues: 이미 알려진 문제점이나 주의사항 등

더 많이 넣으려면 넣을 수 있는데, 이 정도만 되면 함께 contributing 이 가능한 open source project 정도는 될 것입니다.

위의 내용이 어느 정도 만들어진 후에 자유롭게 질문하시면 됩니다.

**Comment by fora22** [comment]
어제 여행을 마치고 돌아왔는데 아직도 여독이 있네요...아무튼!

멘토님이 말해주신 것 처럼 각 프로젝트별로 README 작성한 후 다시 코멘트 드리겠습니다.

**Comment by fora22** [comment]
# README 작성 완료 했습니다!
1. [C++ Socket 통신](https://github.com/fora22/cpp_Network) 
2. [뉴스크롤러](https://github.com/fora22/NewsCrawler)
FlowDebugger는 팀 프로젝트라 README에 대해 얘기할 것이 있어 아직 작성을 못했습니다!
