### ISSUE TITLE
Github License에 관해서

### ISSUE THREAD

**Issue by fora22** [fora22/Coding_Test#21]
#19  에 이어서 License부분에서 인터넷 검색해도 잘 안나오던데 제가 아는건 MIT License밖에 없습니다... 혹시 간단하게 알려주실 수 있을까요?

**Comment by fora22** [comment]
[아 찾았습니다.](https://naver.github.io/OpenSourceGuide/book/UsingOss/the-legal-side-of-opensource.html#licensedef) 라이선스들이 오픈소스와 관련 지어져서 나온 것인거였네요.

**Comment by jongfeel** [comment]
엇 훌륭한 자문자답이군요.

조금 다른 얘기를 해드리면 저는 MIT 라이선스를 좋아하는데
제가 좋아하는 훌륭한 오픈소스들이 거의 MIT 라이선스인 것도 있고
제한되지 않은 자유가 더 좋은 코드를 만들 수 있다는 믿음이 있기도 해서 그렇습니다.

**Comment by fora22** [comment]
MIT License와 BSD, Apache는 [링크](https://naver.github.io/OpenSourceGuide/book/UsingOss/the-legal-side-of-opensource.html#licensedef)의 표를 보면  특징이 똑같던데 제가 알아야할 특징같은것이 있을까요?

**Comment by jongfeel** [comment]
https://deepinsight.tistory.com/82

비슷한 것 같습니다.
Apache만 조금 다르게 상표권 침해 제약만 걸려 있네요.

**Comment by fora22** [comment]
앗 넵 알겠습니다 ㅎㅎ
좋은 자료 감사합니다.
