### ISSUE TITLE
책이 없을 때 활용하면 좋은 사이트

### ISSUE THREAD

**Issue by JSY8869** [fora22/Coding_Test#28]
## 소소한 팁
[이것이 코딩 테스트다!](https://freedeveloper.tistory.com/category/CodingTest/%EC%9D%B4%EA%B2%83%EC%9D%B4%20%EC%BD%94%EB%94%A9%20%ED%85%8C%EC%8A%A4%ED%8A%B8%EB%8B%A4)
- 개인 블로그인데 주인 분이 이것이 코딩 테스트다의 문제들을 잘 정리해 두셔서 필요할 때 활용하면 좋을거 같습니다!

**Comment by fora22** [comment]
와우 홀리 !!!!
꿀팁 감사요~~ ㅎㅎ
