### ISSUE TITLE
Linked List로 구현중에 에러가 발생했는데 이해를 못하겠습니다.

### ISSUE THREAD

**Issue by fora22** [fora22/Coding_Test#3]
![bug1](https://user-images.githubusercontent.com/48875566/96421864-475eec00-1232-11eb-9768-4b3046549c88.PNG)
다음 에러가 발생했는데 [여기](https://github.com/fora22/Coding_Test/blob/fora22/Feature/Stack/Linked_List/VS_Code/DataStructure/Stack/foraStack_Linked_List/foraStackLinkedList.cpp)를 보시면 저는 return 형태가 분명 int인데 class로 인식하네요. 왜 그런지 잘 모르겠습니다;;

**Comment by jongfeel** [comment]
조금 검색해 보시면서 찾아보면 어떨까요? 답을 알려드리기엔 알아야 할 부분이라서요.

https://stackoverflow.com/questions/2808030/subscript-operator-on-pointers

**Comment by fora22** [comment]
아 제가 new연산자로 `newStack`변수가 포인터 변수라서 그런 것 같습니다. 도움 감사합니다 ㅎㅎ
