### ISSUE TITLE
TODO : How to Create a Blog?

### ISSUE THREAD

**Issue by fora22** [fora22/Coding_Test#30]
Blog Design에 있어서 이 이슈에서 의견을 나누었으면 좋겠음

**Comment by JSY8869** [comment]
필요한 기능? 구성을 먼저 생각하는게 좋을거 같아요!
- 메뉴가 있는 메인 페이지
- 익명 채팅방 같은 익명으로 질문하고 답할 수 있는 페이지
- 과제물을 올릴 수 있는 페이지
- 참여권한을 부여하여 권한이 있는 사람만 들어올 수 있도록 하는 기능 (아이디나 간단한 코드를 사용)
- 각자의 정보를 공유할 수 있는 페이지
- 공모전의 보고서를 올릴 수 있는 페이지
- 잡담 게시판 페이지

일단 여기까지 생각해 봤습니다!

**Comment by fora22** [comment]
필요한 기능에서 우선순위를 두자면(개인적으로)

1. 필수
   - 메뉴가 있는 메인 페이지
   - 과제물을 올릴 수 있는 페이지
   - 익명 채팅방 같은 익명으로 질문하고 답할 수 있는 페이지

2. Next
   - 참여권한을 부여하여 권한이 있는 사람만 들어올 수 있도록 하는 기능 (아이디나 간단한 코드를 사용)
   - 각자의 정보를 공유할 수 있는 페이지
   - 공모전의 보고서를 올릴 수 있는 페이지
   - 잡담 게시판 페이지

**Comment by fora22** [comment]
그리고 Blog 만드는 거는 결이 다른 프로젝트이니까 새 레포지토리를 만드는게 낫지 않을까 싶음?

일단 Node.js랑 Django 비교한 글하고 Django 공부한 [레포지토리](https://github.com/fora22/Backend_Practice)는 있음

멘토님께 물어볼까?

**Comment by JSY8869** [comment]
레포지토리는 새로 만드는게 좋을거 같아요!
일단 지금 당장 뭔가를 진행 하기에는 시험기간이라.... 레포지토리 만들면 틈틈히 이것저것 정보는 최대한 찾아서 이슈에 올리겠습니다!

**Comment by fora22** [comment]
[Repository](https://github.com/fora22/CreateBlog) 만들었다~ 초대해줄게
그리고 관련 내용은 Issue에 적어 뒀다가 나중에 [wiki](https://github.com/fora22/CreateBlog/wiki) 정리해두면 좋을 듯. 나중에 찾아보기 힘들어성..ㅎ

README 에 추가하고 싶은 거 있음 추가하셈~
