### ISSUE TITLE
의견 사항

### ISSUE THREAD

**Issue by fora22** [fora22/Coding_Test#8]
# README 관련

README 보면 `Folder Explain`이라는 제목 있는데 해당사항 있으면 적어주셈~(없으면 해당사항 없다고 말해주면 감사)

# Github 관련
## Manage
- issue, Label, Milestone, Project 등 github 관련 tool(?) 들이 있는데 이제 [사용법](https://uang.tistory.com/12)을 다 알게 됨

- 특히 milestone은 그냥 기간 설정해두는 거로 생각했는데 issue들의 그룹을 묶는 역할이였음
- 그래서 Project는 기존 것 다 지우고 Repository Mangae 용 딱 하나만 만듬
- Project에도 Templete 사용해서 자동적으로 [Project Dashboard](https://github.com/fora22/Coding_Test/projects/7)에 올라가도록 했음
    - 예를 들어 issue를 만들면 To do issue 에 자동으로 올라감
    - PR을 만들면 In progress에 올라가고, merge하면 자동으로 Done에 이동됨
- 잘 모르겠으면 전화하셈 ㅋㅋ
## Branch
- 다 사용한 Branch는 삭제하는게 좋을듯 `Edit_README`라던지
- Develope Branch는 의미가 없을듯한데...`fora22/Develope`, `JSY8869/Develope`에서 master로 직접 merge하는게 나아보임(물론 나중에 할 때). 의견 말해주셈

# .gitignore에 관하여
알고 있을지 모르겠는데 .gitignore에 써져있는거는 git을 통해 안올라가게됨. 불필요한 폴더 및 파일을 안올라가게 하는건데(C,C++ 같은 경우 실행할려면 소스코드 이외에 build하게 되면서 부산물들이 생기는데 gitignore에 적어두면 레포지토리에는 안올라가짐) 일일히 작성하기 힘드니까 [사이트](https://www.toptal.com/developers/gitignore) 추천해줄게.

## 사용법
운영체제, 언어, IDE(Visual Studio, Visual Studio Code, IntelliJ, Eclipse 등)를 적어놓고 생성 누르면 만들어짐. 그거 복사해서 *.gitignore* 파일에 넣으면 됨.
**주의할 점은 프로젝트나 소스파일 옆에 각각 두어야 됨.** 이것도 잘 모르겠으면 다시 말해주삼

**Comment by JSY8869** [comment]
# README 관련
작성했습니당~
# Github 관련
학교 한번 가서 제대로 배워야 될거 같아요...
어느정도는 알겠는데 헷갈리는게 너무 많아요....ㅠㅠ
- branch `Edit_README` 삭제했습니다!!
# gitignore 관련
수동으로 체크해제하면서 사용하고 있었는데 일단은 이것두 학교에서 제대로 다시 배우겠슴다...

**Comment by fora22** [comment]
확인~ 학교는 목욜날 갈듯
